CREATE DATABASE IF NOT EXISTS portfolio;
USE portfolio;

CREATE TABLE IF NOT EXISTS assets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type ENUM('stock','fund','bond','cash') NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  name VARCHAR(100),
  quantity DECIMAL(18,4) DEFAULT 0,
  purchasePrice DECIMAL(18,4) DEFAULT 0,
  purchaseDate DATE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);